### ISSUE TITLE
Issues setting values via EEPROM/hceeprom.pl

### ISSUE THREAD

**Issue by ChrisRomp** [zeidlos/hamclock-docker#6]
Thanks for the work you've put into this @zeidlos. How are you feeling about maintaining it? I see some open issues and a PR, with no recent activity on the code. I'd be happy to take on maintenance if you want some help, either here or by splitting the project.

That said, in addition to the problems outlined in #2 and addressed with #5, I'm having an issue with the callsign being set via the run.sh script injecting EEPROM values. Even attaching a shell to the container and running it doesn't seem to make the call sign show up correctly. I've even been talking with the HamClock author, Elwood Downey WB0OEW, about it but this got me thinking, why are we doing this way at all? It's a bit of a hack (Elwood even admits as much in the user contrib for his script) and breaks from some standard Docker conventions.

What I've done in my instance is thrown out the config and calling of `hceeprom.pl` altogether in my version, and instead I'm just mounting a volume to `/root/.hamclock` where it happily persists its configuration. On first run you'll want to trigger a `/restart` and go through the setup process, just like any other instance of HamClock, but I think in the end this might be less prone to quirks and therefore easier to manage.

Thoughts?

**Comment by ChrisRomp** [comment]
Here's my `docker-compose.yaml`:

```yaml
version: "3.7"
services:
  web:
    build: .
    ports:
      - "8081:8081"
      - "8080:8080"
    volumes:
      - hamclock-data:/root/.hamclock
    restart: unless-stopped

volumes:
  hamclock-data:
```

I'll probably add a health check in there for good measure.
